SELECT  SE.SEQ_SUGESTAO_ERRO AS SEQ_SUGESTAO_ERRO
      , A.SEQ_APLICACAO
      , A.APLICACAO
      , A.DESCRICAO AS DESCRICAO_APLICACAO
      , E.TITULO AS ERRO      
      , M.DESCRICAO AS MODULO
      , CONCAT(P.VERSAO, '_', P.SPRINT, '_', P.RELEASE) AS PTF
      
      , ROUND(AVG(R.RATING),1) AS RATING_MEDIO
      , AVG(R.RATING) AS RATING_MEDIO_FULL
      , SUM(R.TOTAL_SIM) AS TOTAL_SIM
      , SUM(R.TOTAL_NAO) AS TOTAL_NAO
FROM RATING R
JOIN  APLICACAO A ON R.SEQ_APLICACAO = A.SEQ_APLICACAO
JOIN  SUGESTAO_ERRO SE ON R.SEQ_SUGESTAO_ERRO = SE.SEQ_SUGESTAO_ERRO
JOIN  MODULO M ON R.SEQ_MODULO = M.SEQ_MODULO
JOIN PTF P ON R.SEQ_PTF = P.SEQ_PTF
JOIN  ERRO E ON SE.SEQ_ERRO = E.SEQ_ERRO
--WHERE E.SEQ_ERRO = 3
GROUP BY
      SE.SEQ_SUGESTAO_ERRO
      , A.SEQ_APLICACAO
      , A.APLICACAO
      , A.DESCRICAO 
      , E.TITULO
      , M.DESCRICAO 
      , P.VERSAO
      , P.SPRINT
      , P.RELEASE;