SELECT A.APLICACAO
    , A.DESCRICAO
    , A.SEQ_MODULO
    , E.SEQ_ERRO
    , E.TITULO
    , E.DESCRICAO
    , E.TAGS
    , E.OCORRENCIA
    , E.RELEVANCIA
    , E.DETALHES
    , E.SEQ_APLICACAO
      
FROM ERRO E
JOIN APLICACAO A ON E.SEQ_APLICACAO = A.SEQ_APLICACAO
AND A.SEQ_APLICACAO = 7;

    
    
     
    
    