SELECT A.SEQ_APLICACAO
        ,	A.APLICACAO
        , 	A.DESCRICAO
        , 	M.SEQ_MODULO
        , 	M.MODULO
        , 	M.SIGLA
        , 	M.DESCRICAO
 
FROM APLICACAO A
	 , MODULO M
WHERE
A.SEQ_MODULO = M.SEQ_MODULO
AND M.SEQ_MODULO = 2;


SELECT A.SEQ_APLICACAO
        ,	A.APLICACAO
        , 	A.DESCRICAO
        , 	M.SEQ_MODULO
        , 	M.MODULO
        , 	M.SIGLA
        , 	M.DESCRICAO
 
FROM APLICACAO A	 
JOIN MODULO M ON M.SEQ_MODULO = A.SEQ_MODULO
WHERE M.SEQ_MODULO = 2;